### ISSUE TITLE
cones kill animals?

### ISSUE THREAD

**Issue by otakup0pe** [CSX8600/trafficcontrol#10]
i've noticed that small animals like vanilla rabbits or mystical world's owls take damage when getting near the cones and channelizers. i can reproduce it pretty solidly. on the dev modpack i've been mucking with.

additional context - survival mode

**Comment by CSX8600** [comment]
Issue has been promoted to [Taiga #67](https://tree.taiga.io/project/cnwaj-csx8600s-mods/us/67)

**Comment by otakup0pe** [comment]
> Issue has been promoted to [Taiga #67](https://tree.taiga.io/project/cnwaj-csx8600s-mods/us/67)

I have no idea what that means but it sounds promising.

**Comment by otakup0pe** [comment]
hmm also i just died by hanging out under a sign. gonna see if i can crafttweaker the problem away for now :eyes:

**Comment by ChrisDemonEye** [comment]
> hmm also i just died by hanging out under a sign. gonna see if i can crafttweaker the problem away for now

This has been a known issue for a little while. A few of our items have improper collision (They're full block collisions and suffocate mobs)

> Issue has been promoted to [Taiga #67](https://tree.taiga.io/project/cnwaj-csx8600s-mods/us/67)

As for this, this just means that the Github issue was added to our development kanban board (Meaning the issue was processed and will be worked on in the future)
