### ISSUE TITLE
Crafting problems

### ISSUE THREAD

**Issue by ExDomino** [CSX8600/trafficcontrol#22]
Hello,

There is some problem with the crafting recipes in your mod.
- Bulbs are all the same crafting.
- Bulbs should not have redstone lamp in their crafting because traffic light frame already have ones.
- Traffic Sensors are not craftable.
- Traffic Light Control Box is not craftable either.
- Poles are too expansive. You should make them craftable by three or four instead of just one.
- Traffic Light Frame 5 bulbs and Doghouse are not craftable.

But I really love your mod. I hope you could fix these recipes.
In our server however, I will fix them with Craftweaker.

**Comment by CSX8600** [comment]
`Bulbs should not have redstone lamp in their crafting because traffic light frame already have ones.` - Changed lamps to redstone in traffic light frame.
`Poles are too expansive. You should make them craftable by three or four instead of just one.` - Changed to receive 3.

All other issues are no longer present.
