### ISSUE TITLE
Bugs with some blocks.

### ISSUE THREAD

**Issue by dldev32** [CSX8600/trafficcontrol#28]
![2021-01-09_20 07 13](https://user-images.githubusercontent.com/65333989/104092564-5d230100-52b7-11eb-86da-d5b374dba620.png)
![2021-01-09_20 07 19](https://user-images.githubusercontent.com/65333989/104092566-5e542e00-52b7-11eb-9c35-dac7031f0ff5.png)

1) Multiblock structures have rendering problems, especially the crossing gate. This problem is the disappearance of the texture when the player is not looking at this block;
2) The crossing gate relay has a problem: when you right-click on it, it falls down, covering some blocks within a radius of 10 meters, while destroying them.

**Comment by CSX8600** [comment]
1. I've done everything I can to try to fix this issue. Unfortunately, due to the way Minecraft works, once the gate block is out of view, it stops rendering everything about it. Since the gate itself isn't a block, there's no way around this. This is a Minecraft limitation.
2. Was not able to replicate this given what you described.

Closing as not fixable/duplicable
