### ISSUE TITLE
trafficlights dont react to Mts cars

### ISSUE THREAD

**Issue by Marci261001** [CSX8600/trafficcontrol#32]
I try to create my own town but ran in to a problem with your traffic lights 
they do not react to my mts cars i tried it with a pig and it worked but with the car it did not how do i fix this

**Comment by ItsJustMiaouss** [comment]
Hi,
I think I found the problem.

In the mod configuration file (``.minecraft/config/trafficcontrol.cfg``), add to the ``S:sensorClasses`` list ``minecrafttransportsimulator.mcinterface.BuilderEntityExisting``. Like this:

```properties
traffic_light {

    S:"sensorClasses" <
        minecrafttransportsimulator.mcinterface.BuilderEntityExisting
        ...
     >

    ...

}
```

This is the class of MTS vehicles.

Also, I suspect that there is a spelling error on [this line](https://github.com/CSX8600/trafficcontrol/blob/master/src/main/java/com/clussmanproductions/trafficcontrol/Config.java#L20). It's not ``minecraftransportsimulator`` but ``minecrafttransportsimulator``

**Comment by CSX8600** [comment]
@ItsJustMiaouss is correct - you have to update the config file. Since these classes can change, there is a built in tool called the `Entity Class Display`. You can turn it on in game by pressing `]` and then looking at any entity in game to figure out what it's class inheritance is (appears at the top of the screen). You can use this information to update your config file accordingly.
