### ISSUE TITLE
Signpack Folder Not Located Correctly on MacOS

### ISSUE THREAD

**Issue by CreativeMasterBonin** [CSX8600/trafficcontrol#74]
I was testing custom sign packs, and when I opened the GUI in the sign, I scrolled to the bottom and found nothing had changed. 
I put in the example pack that was on the tutorial page after restarting the game, and the same thing happened, no changes. Zipping the folders did not work either.

A note about this is that the 'tc_signpacks' folder never generated, I had to add it myself.

here is the game log: https://pastebin.com/agn4Yciw
here is the signs.json code: https://pastebin.com/Ee3h2cBu

Here is an image of the folder setup in the minecraft folder: https://drive.google.com/file/d/1a8grVLWtbRX3U6KQ_LrSTWCM4hH6hr6t/view?usp=sharing

**Comment by GamearooCodes** [comment]
you will need the signs to be in a folder called custom or the shape of your sign then zip custom and the shape folders and signs.json into a zip and add that zip to tc_signpacks then you can press f3 + ] to reload the pack into the game doing that should fix your issue

**Comment by RavenholmZombie** [comment]
Your `signs.json` file is correct, the main issue is that you're not using ZIP archives inside of the `tc_signpacks` folder. You have to use .ZIP files in order for Traffic Control to recognize them, otherwise it won't find them.

After you've put your sign packs into .ZIP folders, you can press `F3 + ]` in-game to do a hot reload which will make Traffic Control look for any new or updated sign packs without having to restart Minecraft.

If you need help making ZIP files on macOS, please refer to this tutorial
https://www.parallels.com/tips/zip-unzip/mac/zip/folder/

**Comment by CreativeMasterBonin** [comment]
Right, so I've zipped my files and reloaded the packs in-game twice.

Nothing changed still even after zipping: https://drive.google.com/file/d/1WkMzl3h5ntvA_l5MzvpvfMDQD6Ap7GXL/view?usp=sharing

I've also tested by downloading sign packs from the server as well and they don't load either.

**Comment by RavenholmZombie** [comment]
Please upload your .ZIP files here so we can take a look at them.

**Comment by CreativeMasterBonin** [comment]
Here is the link to a folder containing the sign packs I'm attempting to use (plus the one I was working on): https://drive.google.com/drive/folders/1LNVa2MqJNuYm6gKfGNP3-uMOKsIRdwde?usp=sharing

**Comment by CSX8600** [comment]
It looks like `US_Toll_Road_Sign_Pack.zip` is the only one that would even be attempted to load, and the json doesn't _seem_ valid, so it won't load either.

Basically, the `signs.json` file needs to be in the root of the zip file for the game to find it. And then all the textures must be in their respective types folders.

**Comment by CreativeMasterBonin** [comment]
I've archived the 'signs.json' and a 'custom' folder (and changed signs.json to reflect this) and the game still refuses to load the pack. I selected the file and folder and zipped them to make a zip file.

The directory path is: minecraft/tc_signpacks/arch.zip
arch.zip: 
signs.json
custom -> is_back.png
-> is.png
-> tbyt.png

**Comment by CSX8600** [comment]
Out of curiosity - are you sure you're looking in the correct `.minecraft` folder? Is your save that you're testing with located in the `saves` folder?

**Comment by CreativeMasterBonin** [comment]
The main (default, vanilla launcher) Minecraft on macOS installation is at: Users/username/Library/Application Support/minecraft
And the tc_signpacks folder is in the 'minecraft' folder. And the save file is in the main 'saves' folder.
There isn't a '.minecraft' by default.

Also, is this supposed to be where the signpacks are located? They are invisible by default... Image link: https://drive.google.com/file/d/1Zh_jFOjZvHbOZYgKwq7Z1j6wbJCRtHoa/view?usp=sharing

anything with '.' prefixed is hidden on macOS by default....

**Comment by CSX8600** [comment]
Ah, I see. So that was going to be my next question if you said it was the proper "`minecraft`" folder. Looks like Java messed up pathing because it's supposed to go one directory up from the `config` directory and do things there. I guess I'll need to look into how to actually do that so it works on macOS too.

In the meantime, if you put your signpacks in that hidden folder you found, then I assume the game will load them since that's where it's apparently looking.

**Comment by RavenholmZombie** [comment]
[rc_signpack.zip](https://github.com/CSX8600/trafficcontrol/files/11400926/rc_signpack.zip)
[US_Toll_Road_Sign_Pack.zip](https://github.com/CSX8600/trafficcontrol/files/11400927/US_Toll_Road_Sign_Pack.zip)
[Custom_Signs.zip](https://github.com/CSX8600/trafficcontrol/files/11400928/Custom_Signs.zip)
[Exit_Number_Signs_Pack.zip](https://github.com/CSX8600/trafficcontrol/files/11400929/Exit_Number_Signs_Pack.zip)

Attached are your sign packs, but fixed. A few of them weren't set up properly.

**Comment by CreativeMasterBonin** [comment]
The packs work in the hidden folder now, whatever was fixed in the zips now has working signs in-game.
