### ISSUE TITLE
Hot Reload Key needs to be remappable

### ISSUE THREAD

**Issue by RavenholmZombie** [CSX8600/trafficcontrol#78]
`F3+]` doesn't work for some non-US QWERTY keyboard layouts, it should be remappable.

**Comment by CSX8600** [comment]
If the issue is due to F3 not being available --

Since F3 is a Minecraft debug key, and because the purpose of hot reload is for debugging, will maintain the standard of using F3. There are a number of articles out there that can help a person remap F3 to a different key.

If the issue is with the `]` key, then this can be reopened and can create an optional keybind.
